### ISSUE TITLE
Still maintained

### ISSUE THREAD

**Issue by trobrock** [thisandagain/queue#15]
Is this project still maintained @thisandagain ?

**Comment by thisandagain** [comment]
It is, though it's stable and I don't have plans to add any additional features myself. That said, any bugs will be responded to quickly! :smile:

**Comment by trobrock** [comment]
Do you have plans to push updates to cocoapods anytime soon? It looks like the version on cocoapods is very out of date with master.

**Comment by thisandagain** [comment]
Of course. Will do.
